### ISSUE TITLE
[Feature] Support SVG

### ISSUE THREAD

**Issue by jfastnacht** [aimeos/aimeos-core#114]
Adding an SVG to a delivery service results in the following error:

```
The image type isn't supported by GDlib., [path to project removed]\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\Media\Image\Standard.php:44
```

Vector graphics should be supported.

**Comment by aimeos** [comment]
Yes, would be nice to have. If you are able to add special handling for SVG, we will merge your PR into the core

**Comment by AndreasA** [comment]
Just wondering but is it working using Imagick class instead of Standard?

**Comment by adimit** [comment]
I'd go about it the following way:

- implement `\Aimeos\MW\Media\Image\Iface` analogous to the `Imagick` class as `SvgImage` or so.
- `save()` would just write the SVG raw, as per suggestion of @AndreasA 
- `scale()` is a no-op
- Add the necessary mime-type based switch into… wherever it needs to be. I honestly don't quite know where.

If you could point me in the right direction, I could make a PR, because we're very interested in the same feature. We'd like to:

- have media items be able to represent SVGs
- associate these with attributes (shouldn't present an issue)
- upload these SVGs via the JQAdmin interface
- (possibly) batch import them, though we'd have to write that import ourselves, which is ok

**Comment by aimeos** [comment]
Based on the mime type, "image/svg+xml" will always create a \Aimeos\MW\Media\Image\Gdlib|Imagick object (depending on the configuration). The solution would be to check in both classes if the mime type is supported by the unterlying library and if not, scaling and converting is skipped.

The only thing that has to be adapted too is the allowed image type configuration for the media controller: https://github.com/aimeos/aimeos-core/blob/master/controller/common/src/Controller/Common/Media/Standard.php#L377

Admin image templates, media controller and batch import are no problem if \Aimeos\MW\Media\Image\Gdlib|Imagick classes are enhanced.

**Comment by aimeos** [comment]
Implemented in https://github.com/aimeos/aimeos-core/commit/c3d4924b39e31d76e96a9b64dd87b63f346655bc
