### ISSUE TITLE
missing directory exists check

### ISSUE THREAD

**Issue by xerc** [aimeos/aimeos-core#217]
@ ext/test/manifest.php
>        'setup' => ['lib/custom/setup']

`$ php artisan aimeos:setup` breaks if folder wihin EXT path is missing; ext/test/lib/custom/setup
https://github.com/aimeos/aimeos-core/blob/eb2e68fe2f0bfb73c8ac806b9fa24ef2db6a9b85/lib/mwlib/src/MW/Setup/Manager/Base.php#L120

**Comment by aimeos** [comment]
We could add a `file_exists()` check here but this could lead to hard to find errors if the entry in the manifest.php or the setup directory are not named the same (e.g. due to a spelling issue). Thus, we made sure that there's a `.gitkeep` file in `lib/custom/setup` for newly created extensions, so this directory isn't a problem when you check out the extension from a Git repository (which doesn't create empty directories).
