### ISSUE TITLE
Error after composer update 

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/aimeos-core#231]
PostgreSQL 9.6.15
Laravel Framework 8.37.0
PHP 7.4.16
"php": "^7.3|^8.0",
"aimeos/aimeos-laravel": "dev-master",

Error after composer update Attached.

correct syntax:
```
ALTER TABLE public.mshop_locale_site
  DROP CONSTRAINT mshop_locale_site_siteid_key cascade 
```
![Capture](https://user-images.githubusercontent.com/7951825/116791899-e485c180-aaac-11eb-866e-863a302dfc41.JPG)

**Comment by aimeos** [comment]
That's a bit more complicated because as far as we can see, this happens during the Doctrine DBAL schema update so it's not possible to change a SQL statement here because all is generated by Doctrine DBAL.

The next problem is that we can't reproduce the issue because in our test setup, there is no such index. If you drop the index `mshop_locale_site_siteid_key`, does it work if you run the setup several time afterwards?

**Comment by MahmoudDevo** [comment]
**YES,** i do that every setup in the database : 
ALTER TABLE public.mshop_locale_site
  DROP CONSTRAINT mshop_locale_site_siteid_key cascade ;
Thank you

**Comment by aimeos** [comment]
What PostgreSQL version do you use?

**Comment by MahmoudDevo** [comment]
Postgresql 9.6+ AND 12.
