### ISSUE TITLE
First order is not matched to new created customer account

### ISSUE THREAD

**Issue by nvindice** [aimeos/aimeos-core#273]
When issuing an order as a guest and then checking the "Create an account" box, the user account is created but the order is not matched to the new account.

This most likely happens because the order is stored first via the `store()` method in the Frontend Basket Controller and the new customer is created afterwards (!) `Html\Checkout\Standard\Process\Account\Standard`. What can I do?

**Comment by nvindice** [comment]
Hi @aimeos,
sorry for asking again but I'd love to get some feedback on this issue. I'm afraid I don't understand the underlying manager/submanager system good enough to understand how the described order of events can be fixed. Or am I missing something else?

**Comment by aimeos** [comment]
This might be due to the change that the order is now stored first so the subparts have access to the order ID:
https://github.com/aimeos/ai-client-html/commit/04cac77ca6fe2a0bc104c6c0ec5ec2684f3ec93f#diff-dce2a927bfb34f4d328fabe11cbaeb67974b02abf74c9f42e20f99a798097b32

Maybe it's better to revert that and if someone needs access to the order ID, a decorator is the better alternative.

**Comment by nvindice** [comment]
I agree, as storing the customer id is a mandatory feature IMO. Can you do it?

**Comment by aimeos** [comment]
Done in dev-master and 2021.10.x-dev

**Comment by nvindice** [comment]
Thank you!
