### ISSUE TITLE
Statistics graph, financial book keeping automation required. Tax handling / law conformity improvements.

### ISSUE THREAD

**Issue by faerietree** [aimeos/aimeos-core#73]
Friends for whom I host websites decided against Aimeos and for Gambio due to the following reasons:
- Graphs at start page.
- Inclusion of financial book keeping functionality like e.g.
  - Delivery note,
  - Invoice generation,
  - Tax handling,
- German law conformity (like Kleinunternehmerregelung)
This list is incomplete and it was what I figured out of comparing what convinced them of Gambio. Actually many of the things they liked so much about Gambio Aimeos also supports out of the box. Yet they always found other reasons. And the list is what it bolted down to as far as I could assemble quickly now.

Gambio forces a support contract
---
The forced support contract of 1 year costing 150 € (at time of writing) did not stop their conviction of Gambio.

Aimeos source code easy to find, contribute, while Gambio source code difficult to find.
---
*Finding Gambio up to date/development source code turns out to be complicated. This implies that edge updates and development for hotfixes et alia are much more difficult than in Aimeos.*

Open source prejudice
---
Also they thought "due to the price" Gambio must be commercial and they think open source is inferior because I already made them use FreeCAD. Poor FreeCAD, poor Aimeos whose major advantage seems its tight integration with so many content management systems.
I will later today tell them about the Content Management System integration of Aimeos and that Gambio is open source too. So that both (and not only Aimeos) are "minor" following their terms. Strange world - only few know the true powers of open source.

Idea: Conversion factor automation
---
"Als Basis wird im Shop eine Standardwährung bestimmt, für jede weitere Währung wird dann lediglich noch der Umrechnungskurs hinterlegt." [Gambio Features Auflistung]
If we were to code this in Aimeos using a parser - we might reduce the manual updating of the conversion factors.

Aimeos development contribution outlook
---
If they had decided for Aimeos, then I might have been in the position to develop missing features, while now I have to get into Gambio internals instead ...
I will compare carefully and try to iron out issues in Aimeos that I think are handled great in Gambio. Note I'm just a part time hobby developer and the hosting I do for friends and not commercially, world development, engineering and open farming is taking most resources.

**Comment by aimeos** [comment]
Thank you for the insights!

Aimeos is not for everyone. Especially, it's not tailored for very small businesses (Kleinunternehmer) which want features that are usually better handled in a specialized accounting software. For example, invoice generation requires continuous invoice numbers but that's not true for the order IDs in Aimeos. Also, the currency handling is tailored for mid to big size businesses because they want psychological prices (3.99 instead of 4.13 due to automatic currency conversion). Extensions for invoice and automatic currency conversion can be developed (Aimeos is very flexible about that) but it's not our main focus.

Nevertheless, some of your listed issues are already possible of in development:
- There will be a dashboard with nice graphs in one of the next versions
- Delivery notification e-mails are already available
- For the "Kleinunternehmerregelung" you only need to set the tax rate to 0.00

If you find out more reasons why they prefer other systems instead of Aimeos, it would be great to drop us a note.

Regarding Open Source and support contracts: They can buy a support contract from the [Aimeos company](https://aimeos.com/support/) too, but they are not forced to. There will be a support contract for getting updates for the LTS versions after one year. They either have to buy it to be able to use the software securely afterwards or they have to upgrade every two years.

**Comment by aimeos** [comment]
This is a screenshot of the new dashboard for the upcoming Aimeos version: ![Dashboard](https://cloud.githubusercontent.com/assets/8647429/16496612/15b0f6ce-3ef3-11e6-94d2-32b7bd05fba2.png)

**Comment by faerietree** [comment]
Hehe, how epic!!
