### ISSUE TITLE
Feature Request: enable ticket sales

### ISSUE THREAD

**Issue by vmans** [aimeos/aimeos-core#85]
I keep my request simple in this stage. And execution should choose the easiest solution, if it's a go. 

Specifications
---
1. Download or send tickets to buyer. On the ticket, there is a QR code.
2. If a customer buys two or more tickets, he downloads that number of files with a unique QR code. So one file equals one ticket.

Remarks
---
- In simple cases, one download and one QR-code is enough, even for groups. If the request is complex to handle, perhaps start with this?
- A barcode for event organizers who only carry barcode reading equipment.
- Combined sales should be possible, at least in a later stage. For instance, a customer buys one book and one or more entrance tickets in one sale.

Towards a solution
---
- Now there is a download product already in Aimeos. Perhaps extend that? In general, customers expect PDF perhaps, but a printable mail will do (in the beginning at least).
- How to generate a QR-code per ticket, must be configurable. For instance [time + name + zipcode + housenr + country iso2 + ordernumber + ticketnumber].

---

I'm not a programmer, otherwise I should have created this already I think, as an extension. But it's a value adding feature for Aimeos, I think, it might fit into the core.

**Comment by aimeos** [comment]
The solution is to extend the payment e-mail HTML client that generates the order confirmation. There you can attach the PDF with the tickets and QR-Code. PDFs are very specific to the shop because of the design and (usually) information. That's the reason why Aimeos doesn't attach a PDF of the order by default.

You have to implement this for your customer. If you can't, there are several parties available you can pay for helping you.
