### ISSUE TITLE
[Feature] Derive bundle price from all products contained.

### ISSUE THREAD

**Issue by faerietree** [aimeos/aimeos-core#92]
Currently the price has to be set manually and whenever a price changes or a rebate is added, the price has to be recalculated. Some ideas:

* Maybe a price type automatic could be useful to still allow manual price.
* If the price is set to 0, calculate the price automatically and use the set currency.

Example bundle:
https://hamag-maschinenbau.de/index.php?id=12&L=43&ai[controller]=Catalog&ai[action]=detail&ai[d_name]=S%C3%A4gen_und_Anschleifen_mit_LAPIDA-Maschinen&ai[d_prodid]=453

As an alternative one could - instead of one bundle - add all products into the basket (as is done on Amazon with "buy together|all"). Though that's redundant with `bought together` Aimeos product associations.

**Comment by aimeos** [comment]
That's a very special case because bundles do usually have a lower price than the sum of the products. Maybe a bundle is not what you need for this. You could create a modified detail or list view that puts all listed products into the basket at once like you've pointed out. The "bought together" is more like Amazons "customers who bought this also bought" ...
