### ISSUE TITLE
[Feature] Generate PDF invoices from HTML

### ISSUE THREAD

**Issue by faerietree** [aimeos/aimeos-core#95]

**Comment by faerietree** [comment]
Ideally provided in the order history of accounts as well as attached to order confirmation mails (maybe).

**Comment by aimeos** [comment]
For invoices you need data that isn't present in Aimeos, such as the seller address, VAT ID, bank account and others. An option would be to require a PDF template that can be filled with the order data but one major problem will remain: These PDFs need a fixed layout because working with PDFs is like drawing in a vector painting program.

**Comment by faerietree** [comment]
hm. Using a new scheduler job that is at least as frequent as `Payment related email` the invoices can be directly generated from the HTML. Maybe this is more suitable for a separate extension (TYPO3 in the case of @HAMAG & @worlddevelopment).

Also instead of attaching directly to the email it might be wiser to rather insert a link into the Email.

The extra information is doable.
Thank you for the feedback. :-)
